#!/bin/bash

# This has so far only been tested in Fedora 42

# Get user input
echo "What battery percentage should this laptop STOP charging at? (Number only)"
read -p "Percentage: " entry 

# Clean up input
removecharacter="%"
stopnumber="${entry//$removecharacter}"

# Charging-start threshold: (default to 0, meaning charge anytime under stop threshold)
sudo tee /sys/class/power_supply/BAT0/charge_start_threshold <<< "0" 

# Charging-stop threshold:
sudo tee /sys/class/power_supply/BAT0/charge_stop_threshold <<< "$stopnumber"
