#!/bin/bash

# Set up error handling
set -e
trap 'echo Problem encountered on line $LINENO. Code: $?.' ERR

echo "Please enter each Application ID, a space between each. Press 'Enter', then 'Ctrl+D' when finished."

while read line
do
    entryarray=("${entryarray[@]}" $line)
done

for item in "${entryarray[@]}"
do 
    flatpak install flathub $item -yy
done
