#!/bin/bash

# Designed for Linux Mint 20 with Cinnamon


##############   Basic Setup for script   ##############

# Run in home dir
cd ~
# Set up error handling
set -e
trap 'echo Problem encountered on line $LINENO. Code: $?.' ERR
# Create output file in home directory
touch LM-auto-setup-output.txt
# Create Counter
counter=0


##############   Get user input   ##############

read -p "What apt packages should be REMOVED? (space between each) " removeentry
# simple-scan thunderbird transmission-gtk rhythmbox warpinator pix
read -p "What apt packages should be INSTALLED? (space between each) " installentry
# steam htop xscreensaver* pdftk-java 
read -p "How many workspaces do you want? " workspacecount

##############   WiFi powersave   ##############

sudo sed -i 's/3/2/' /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
counter=$((counter+1))
echo "${counter}) WiFi powersave set up." | tee -a LM-auto-setup-output.txt


##############   Remove unecessary apps   ##############

sudo apt purge $removeentry -y
counter=$((counter+1))
echo "${counter}) Superfluous apps removed" | tee -a LM-auto-setup-output.txt


##############   Update repos and upgrade default apps   ##############

sudo apt update -qq
counter=$((counter+1))
echo "${counter}) APT update complete." | tee -a LM-auto-setup-output.txt
sudo apt upgrade -y
counter=$((counter+1))
echo "${counter}) APT upgrade complete." | tee -a LM-auto-setup-output.txt


##############   Install ATP packages   ##############

sudo apt install $installentry -y 
counter=$((counter+1))
echo "${counter}) APT package installations complete." | tee -a LM-auto-setup-output.txt


##############   Cleanup   ##############

sudo apt autoclean -y
counter=$((counter+1))
echo "${counter}) Autoclean successful." | tee -a LM-auto-setup-output.txt
sudo apt autoremove -y
counter=$((counter+1))
echo "${counter}) Autoremove successful." | tee -a LM-auto-setup-output.txt


##############   Set workspace count   ##############

gsettings set org.cinnamon.desktop.wm.preferences num-workspaces $workspacecount
counter=$((counter+1))
echo "${counter}) Workspaces set up." | tee -a LM-auto-setup-output.txt


##############   Finished   ##############

counter=$((counter+1))
echo -e "\n${counter}) Done. You should see ${counter} seqential outputs." | tee -a LM-auto-setup-output.txt
