#!/bin/bash

# Designed for Nobara 41 with Gnome

# Remove unecessary apps
ead -p "What dnf packages should be REMOVED? (space between each) " removeentry
sudo dnf -y remove $removeentry
# openrgb rhythmbox gedit

# Add desired apps
read -p "What dnf packages should be INSTALLED? (space between each) " installentry
sudo dnf -y install $installentry
# xed fastfetch thunar

# Add desired flatpacks
flatpak install flathub com.vscodium.codium com.mattjakeman.ExtensionManager com.github.maoschanz.drawing -yyyyyy

# A little reminder
echo "To show day of week in top bar: open dconf editor > org > gnome > desktop > interface > toggle "clock-show-date" to on"