#!/bin/bash

# Designed for Ubuntu 24.04 with Gnome


##############   Basic Setup for script   ##############

# Run in home dir
cd ~
# Set up error handling
set -e
trap 'echo Problem encountered on line $LINENO. Code: $?.' ERR
# Create output file in home directory
touch Ubuntu-setup-log.txt
# Create Counter
counter=0


##############   Get user input   ##############

read -p "What apt packages should be REMOVED? (space between each) " removeentry
# nautilus totem thunderbird remmina rhythmbox
read -p "What apt packages should be INSTALLED? (space between each) " installentry
# steam p7zip-full htop nvtop pdftk-java ubuntu-restricted-extras vlc gnome-tweaks thunar firefox vlc thunar
read -p "How many workspaces do you want? " workspacecount

##############   WiFi powersave   ##############

sudo sed -i 's/3/2/' /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
counter=$((counter+1))
echo "${counter}) WiFi powersave set up." | tee -a Ubuntu-setup-log.txt


##############   Remove unnecessary apps   ##############

sudo apt purge $removeentry -y


##############   Update repos and upgrade default apps   ##############

sudo apt update -qq
counter=$((counter+1))
echo "${counter}) APT update complete." | tee -a Ubuntu-setup-log.txt
sudo apt upgrade -y
counter=$((counter+1))
echo "${counter}) APT upgrade complete." | tee -a Ubuntu-setup-log.txt


##############   Install ATP packages   ##############

sudo apt install $installentry -y 
counter=$((counter+1))
echo "${counter}) APT package installations complete." | tee -a Ubuntu-setup-log.txt


##############   APT Cleanup   ##############

sudo apt autoclean -y
counter=$((counter+1))
echo "${counter}) Autoclean successful." | tee -a Ubuntu-setup-log.txt
sudo apt autoremove -y
counter=$((counter+1))
echo "${counter}) Autoremove successful." | tee -a Ubuntu-setup-log.txt


##############   Set workspace count   ##############

gsettings set org.gnome.mutter dynamic-workspaces false
gsettings set org.gnome.desktop.wm.preferences num-workspaces $workspacecount


##############   Finished   ##############

counter=$((counter+1))
echo -e "\n${counter}) Done. You should see ${counter} seqential outputs." | tee -a Ubuntu-setup-log.txt